---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Installing docker dependencies
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Installing GPG key 
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present


    - name: Installing Docker
      apt: name=docker-ce update_cache=yes state=present
 
    - name: Configuring /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.200.10 manager.kuberlab.intranet manager
        - 192.168.200.20 node01.kuberlab.intranet node01          
        - 192.168.200.30 node02.kuberlab.intranet node02
        - 192.168.200.40 node03.kuberlab.intranet node03
